test: &default

  # Credentials for REST APIs
  client_id: Ac-AguEOag1S8MzcU2AxpLyd9b3rSPhqtPEnrC10X44d0zHWT2-FeVgmUBIuWZ9koQtnurdulecr_iQJ
  client_secret: EPZ2KlR6xUitk0_Xc4CCeh6lA5hRvqS5uqQ41cBtmpK4IdVxC8AVtVKhYlFgv63CdN1omNRn6qAXRC9H

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: jorge.alfaro@hotmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
