# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4f92e7b156e67f73948bccc8a6e4455f94bbce5f9e37ba6d1126ee16d66e700d0f17d36f3ab0af9a62b94843926b4838736ef81195510e23eb0d0657115d8af

test:
  secret_key_base: edcb075435193b459fd0f4f234083f3e917a6289a9a349c77b772f32a4b3338bdcf61a741a298a9de663977691f0503d3af26779b32453c8013b8132268ed42a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
